# Generated by Django 5.0 on 2024-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modeler", "0004_chat_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last time the diagram was accessed"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(
                default="Untitled diagram",
                max_length=64,
                unique=True,
                verbose_name="name of the diagram",
            ),
        ),
    ]
