# Generated by Django 5.0 on 2024-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modeler", "0005_chat_last_modified_alter_chat_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(
                default="Untitled diagram",
                max_length=64,
                verbose_name="name of the diagram",
            ),
        ),
    ]
