# Generated by Django 5.0 on 2024-06-12 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("modeler", "0006_alter_chat_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="last_modified",
        ),
    ]
