# Generated by Django 5.0 on 2024-06-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modeler", "0007_remove_chat_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last time the diagram was accessed"
            ),
        ),
    ]
