# Generated by Django 5.0 on 2024-06-13 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modeler", "0008_chat_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="diagram",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="modeler.chat",
            ),
            preserve_default=False,
        ),
    ]
