# Generated by Django 5.0 on 2024-06-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modeler", "0010_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Format",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name="file",
            name="format",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="modeler.format",
            ),
            preserve_default=False,
        ),
    ]
