# Generated by Django 5.0 on 2024-06-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modeler", "0011_format_file_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="software",
            field=models.CharField(
                choices=[("G", "gojs"), ("P", "plantuml"), ("M", "mermaid")],
                default="P",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="modeler/diagrams/"),
        ),
        migrations.AlterField(
            model_name="format",
            name="value",
            field=models.CharField(
                choices=[("png", "png"), ("svg", "svg")], max_length=3, unique=True
            ),
        ),
    ]
